config/routes.rb
Rails.application.routes.draw do
  root to: 'enrico_items#index'
  resources :enrico_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrico_item.rb
class EnricoItem < ApplicationRecord
  has_one_attached :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enrico_items_controller.rb
class EnricoItemsController < ApplicationController
  def index
    @items = EnricoItem.all
  end

  def new
    @item = EnricoItem.new
  end

  def create
    @item = EnricoItem.create!(item_params)
    redirect_to EnricoItem
  end

  def destroy
    @item = EnricoItem.find(params[:id])
    name = @item.content_blob.filename
    @item.destroy
    flash[:success] = "Successfully removed #{name}"
    redirect_to EnricoItem
  end


  private

  def item_params
    params.require(:enrico_item).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/enrico_items/index.html.slim
= link_to 'Добавить', new_enrico_item_path, class: 'btn btn-default'

table.table
  thead
    tr
      th Filename
      th
  tbody
    - @items.each do |item|
      tr
        td= item.content_blob.filename
        td
          = link_to 'View', item.content_blob.service_url, target: '_blank', class: 'btn btn-default'
          = ' '
          = link_to 'Download', item.content_blob.service_url(disposition: :attachment), class: 'btn btn-default'
          = ' '
          = link_to 'Remove', item, method: :delete, class: 'btn btn-danger', data: {confirm: 'Please confirm'}

app/views/enrico_items/new.html.slim
= simple_form_for @item do |f|
  = f.input :content, as: :file
  = f.button :submit, 'Загрузить'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Демо загрузки файлов</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= content_tag :li, class: (controller_name == 'enrico_items' ? 'active' : '') do %>
            <%= link_to 'Элементы контента', enrico_items_path %>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
        </button>
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>